# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
    sdz_user.registration_complet:
        class: AppBundle\EventListener\RegistrationConfirmListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }
    acme.js_vars:
        class: stdClass
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    app.name_formatter:
        class: AppBundle\Service\NameFormatter
    app.twig.name_formatter_extension:
        class: AppBundle\Service\NameFormatterExtension
        arguments:
            - "@app.name_formatter"
        tags:
            - { name: twig.extension }
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        public: false
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%'}