# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
    acme.js_vars:
        class: stdClass
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    app.name_formatter:
        class: AppBundle\Service\NameFormatter
    app.twig.name_formatter_extension:
        class: AppBundle\Service\NameFormatterExtension
        arguments:
            - "@app.name_formatter"
        tags:
            - { name: twig.extension }
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;dbname=%database_name%"
            - "%database_user%"
            - "%database_password%"
        calls:
            - [ setAttribute, [3,2]]
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - "@pdo"
            - { lock_mode: 0 }
    topic.gameplay:
        class: AppBundle\Socket\GamePlayTopic
        arguments:
            - "@gos_web_socket.websocket.client_manipulator"
            - "@doctrine"
        tags:
            - { name: gos_web_socket.topic }
#    user.registration_complete:
#        class: UserBundle\Listener\RegistrationListener
#        arguments:
#            - "@router"
#        tags:
#            - { name: kernel.event_subscriber }
