<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function autocomplete($term, $excludedName){
        return $this->_em->createQueryBuilder()
            ->select('u.username')
            ->from($this->_entityName, 'u')
            ->where('u.username LIKE :term')
            ->andWhere('u.username <> :excludedName')
            ->setParameter('term', '%' . $term . '%')
            ->setParameter('excludedName', $excludedName)
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();
    }
}
