game_edition:
    path: /edition-partie/{idGame}
    defaults:
        _controller: AppBundle:GameEditor:edit
    methods: [GET]

game_edition_ajax:
    path: /_ajax/edit-game
    defaults:
        _controller: AppBundle:GameEditor:editAjax
    methods: [GET, POST]
    options:
        expose: true

game_edition_autocomplete:
    path: /_ajax/edit-game-autocomplete-username
    defaults:
        _controller: AppBundle:GameEditor:autocomplete
    methods: [GET]
    options:
        expose: true

edit_character:
    path: /edition-personnage/{idGame}
    defaults:
        _controller: AppBundle:CharacterEditor:editCharacter
    methods: [GET]

edit_character_ajax:
    path: ajax/edit-character
    defaults:
        _controller: AppBundle:CharacterEditor:editCharacterAjax
    methods: [GET, POST]